const $=s=>document.querySelector(s);const fakeUsers=[['林默','林','avatar-a'],['Kevin','K','avatar-b'],['Mia','M','avatar-c']];
let state=JSON.parse(localStorage.getItem('teamask')||'null')||{name:'',sessions:[],active:null,config:{baseUrl:'',endpoint:'/chat/completions',key:'',model:'gpt-4o-mini'}};if(state.config.url&&!state.config.baseUrl){const old=state.config.url;state.config.baseUrl=old.replace(/\/(?:responses|chat\/completions)\/?$/,'');state.config.endpoint=old.includes('/responses')?'/responses':'/chat/completions'}state.config.endpoint=state.config.endpoint||'/chat/completions';let aiOn=true;
function save(){localStorage.setItem('teamask',JSON.stringify(state))}function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,5)}function esc(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function newSession(){const s={id:uid(),title:'新的对话',time:new Date().toLocaleDateString('zh-CN',{month:'short',day:'numeric'}),messages:[]};state.sessions.unshift(s);state.active=s.id;save();render()}
function activeSession(){return state.sessions.find(s=>s.id===state.active)}
function render(){if(!state.name)return;$('#nameGate').classList.add('hidden');$('#app').classList.remove('hidden');$('#profileName').textContent=state.name;$('#profileAvatar').textContent=state.name.slice(0,2);$('#sessionList').innerHTML=state.sessions.map(s=>`<div class="session ${s.id===state.active?'active':''}" data-id="${s.id}"><div class="session-title">${esc(s.title)}</div><div class="session-time">${s.time}</div></div>`).join('');document.querySelectorAll('.session').forEach(e=>e.onclick=()=>{state.active=e.dataset.id;save();render()});const msgs=activeSession()?.messages||[];$('#messageList').innerHTML='<div class="day-divider">今天 · PUBLIC ROOM</div>'+msgs.map(messageHTML).join('');$('#messageList').scrollTop=$('#messageList').scrollHeight;$('#modelBadge').textContent=state.config.model||'未设置模型'}
function messageHTML(m){const me=m.author===state.name,ai=m.kind==='ai';return `<article class="message ${me?'me':''} ${ai?'ai':''}"><div class="avatar ${m.avatar||'avatar-me'}">${esc(m.initials||m.author.slice(0,2))}</div><div class="message-body"><div class="message-meta">${esc(m.author)} ${ai?'<span class="ai-label">AI · '+esc(m.model||state.config.model)+'</span>':''}<span>${m.time}</span></div><div class="bubble ${m.pending?'pending-bubble':''}">${m.pending?'<span class="thinking"><i></i><i></i><i></i> 正在思考…</span>':esc(m.text).replace(/\n/g,'<br>')}</div></div></article>`}
function addMessage(m){const s=activeSession();s.messages.push(m);if(s.title==='新的对话'&&m.author===state.name)s.title=m.text.slice(0,25);save();render()}
async function askAI(){const s=activeSession(),c=state.config,url=(c.baseUrl||'').replace(/\/$/,'')+c.endpoint;if(!aiOn)return;const pending={author:c.model||'AI',initials:'AI',avatar:'avatar-c',kind:'ai',model:c.model||'AI',pending:true,time:now()};s.messages.push(pending);save();render();if(!c.baseUrl||!c.key){pending.pending=false;pending.text='请先在设置中填写 API 基础地址和 Key。';save();render();return}try{const messages=s.messages.filter(m=>!m.pending).map(m=>({role:m.kind==='ai'?'assistant':'user',content:m.author+': '+m.text}));const isResponses=c.endpoint==='/responses';const body=isResponses?{model:c.model,input:messages.map(m=>`${m.role==='assistant'?'AI':m.content.split(': ')[0]}: ${m.content.includes(': ')?m.content.slice(m.content.indexOf(': ')+2):m.content}`).join('\n')}:{model:c.model,messages};const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url,key:c.key,body})});const d=await r.json();if(!r.ok)throw new Error(d.error||'代理请求失败');pending.pending=false;pending.text=d.output_text||d.choices?.[0]?.message?.content||d.output?.flatMap(x=>x.content||[]).map(x=>x.text||'').join('')||'模型没有返回内容。';pending.time=now();save();render()}catch(e){pending.pending=false;pending.text='请求失败：'+e.message;pending.time=now();save();render()}}
function now(){return new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}
$('#nameForm').onsubmit=e=>{e.preventDefault();const n=$('#nameInput').value.trim();if(!n)return;state.name=n;if(!state.sessions.length)newSession();else render()};$('#newSessionBtn').onclick=newSession;$('#renameBtn').onclick=()=>{const n=prompt('输入新名字',state.name);if(n?.trim()){state.name=n.trim();save();render()}};$('#messageForm').onsubmit=e=>{e.preventDefault();const input=$('#messageInput'),text=input.value.trim();if(!text)return;addMessage({author:state.name,initials:state.name.slice(0,2),avatar:'avatar-me',text,time:now()});input.value='';input.style.height='auto';askAI()};$('#messageInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#messageForm').requestSubmit()}else if(e.key==='Enter'&&e.shiftKey){setTimeout(()=>e.target.style.height=e.target.scrollHeight+'px')}};$('#aiToggle').onclick=()=>{aiOn=!aiOn;$('#aiToggle').classList.toggle('on',aiOn);$('#aiToggle').setAttribute('aria-pressed',aiOn)};
function openSettings(){$('#apiBaseUrl').value=state.config.baseUrl;$('#apiEndpoint').value=state.config.endpoint;$('#apiKey').value=state.config.key;$('#apiModel').value=state.config.model;$('#settingsDialog').showModal()}$('#settingsBtn').onclick=openSettings;$('#modelSettings').onclick=openSettings;$('#closeSettings').onclick=()=>$('#settingsDialog').close();$('#saveSettings').onclick=()=>{state.config={baseUrl:$('#apiBaseUrl').value.trim(),endpoint:$('#apiEndpoint').value,key:$('#apiKey').value.trim(),model:$('#apiModel').value.trim()||'gpt-4o-mini'};save();$('#settingsDialog').close();render()};$('#clearSettings').onclick=()=>{$('#apiBaseUrl').value='';$('#apiEndpoint').value='/chat/completions';$('#apiKey').value='';$('#apiModel').value='gpt-4o-mini'};
if(state.name)render();else $('#app').classList.add('hidden');$('#aiToggle').classList.add('on');
